version: '3.1'
services:
  jiang-zipkin:
    restart: always
    image: 35.241.113.30:5000/jiang-zipkin
    container_name: jiang-zipkin
    ports:
      - 9411:9411
    networks:
      - zipkin_network
networks:
  zipkin_network: